// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestExecutionService.proto

// Protobuf Java Version: 3.25.1
package pfl.test_execute;

public final class TestExecutionService {
  private TestExecutionService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ipAddr = 1;</code>
     * @return The ipAddr.
     */
    java.lang.String getIpAddr();
    /**
     * <code>string ipAddr = 1;</code>
     * @return The bytes for ipAddr.
     */
    com.google.protobuf.ByteString
        getIpAddrBytes();

    /**
     * <code>string uuid = 2;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();
  }
  /**
   * Protobuf type {@code ClientID}
   */
  public static final class ClientID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientID)
      ClientIDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientID.newBuilder() to construct.
    private ClientID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientID() {
      ipAddr_ = "";
      uuid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientID();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pfl.test_execute.TestExecutionService.internal_static_ClientID_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pfl.test_execute.TestExecutionService.internal_static_ClientID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pfl.test_execute.TestExecutionService.ClientID.class, pfl.test_execute.TestExecutionService.ClientID.Builder.class);
    }

    public static final int IPADDR_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ipAddr_ = "";
    /**
     * <code>string ipAddr = 1;</code>
     * @return The ipAddr.
     */
    @java.lang.Override
    public java.lang.String getIpAddr() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAddr_ = s;
        return s;
      }
    }
    /**
     * <code>string ipAddr = 1;</code>
     * @return The bytes for ipAddr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpAddrBytes() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UUID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 2;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipAddr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ipAddr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uuid_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipAddr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ipAddr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uuid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pfl.test_execute.TestExecutionService.ClientID)) {
        return super.equals(obj);
      }
      pfl.test_execute.TestExecutionService.ClientID other = (pfl.test_execute.TestExecutionService.ClientID) obj;

      if (!getIpAddr()
          .equals(other.getIpAddr())) return false;
      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IPADDR_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddr().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pfl.test_execute.TestExecutionService.ClientID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pfl.test_execute.TestExecutionService.ClientID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pfl.test_execute.TestExecutionService.ClientID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pfl.test_execute.TestExecutionService.ClientID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientID)
        pfl.test_execute.TestExecutionService.ClientIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pfl.test_execute.TestExecutionService.internal_static_ClientID_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pfl.test_execute.TestExecutionService.internal_static_ClientID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pfl.test_execute.TestExecutionService.ClientID.class, pfl.test_execute.TestExecutionService.ClientID.Builder.class);
      }

      // Construct using pfl.test_execute.TestExecutionService.ClientID.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ipAddr_ = "";
        uuid_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pfl.test_execute.TestExecutionService.internal_static_ClientID_descriptor;
      }

      @java.lang.Override
      public pfl.test_execute.TestExecutionService.ClientID getDefaultInstanceForType() {
        return pfl.test_execute.TestExecutionService.ClientID.getDefaultInstance();
      }

      @java.lang.Override
      public pfl.test_execute.TestExecutionService.ClientID build() {
        pfl.test_execute.TestExecutionService.ClientID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pfl.test_execute.TestExecutionService.ClientID buildPartial() {
        pfl.test_execute.TestExecutionService.ClientID result = new pfl.test_execute.TestExecutionService.ClientID(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pfl.test_execute.TestExecutionService.ClientID result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ipAddr_ = ipAddr_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.uuid_ = uuid_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pfl.test_execute.TestExecutionService.ClientID) {
          return mergeFrom((pfl.test_execute.TestExecutionService.ClientID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pfl.test_execute.TestExecutionService.ClientID other) {
        if (other == pfl.test_execute.TestExecutionService.ClientID.getDefaultInstance()) return this;
        if (!other.getIpAddr().isEmpty()) {
          ipAddr_ = other.ipAddr_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                ipAddr_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                uuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object ipAddr_ = "";
      /**
       * <code>string ipAddr = 1;</code>
       * @return The ipAddr.
       */
      public java.lang.String getIpAddr() {
        java.lang.Object ref = ipAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ipAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ipAddr = 1;</code>
       * @return The bytes for ipAddr.
       */
      public com.google.protobuf.ByteString
          getIpAddrBytes() {
        java.lang.Object ref = ipAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ipAddr = 1;</code>
       * @param value The ipAddr to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddr(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ipAddr_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string ipAddr = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpAddr() {
        ipAddr_ = getDefaultInstance().getIpAddr();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string ipAddr = 1;</code>
       * @param value The bytes for ipAddr to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ipAddr_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 2;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 2;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 2;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uuid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        uuid_ = getDefaultInstance().getUuid();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 2;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uuid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientID)
    }

    // @@protoc_insertion_point(class_scope:ClientID)
    private static final pfl.test_execute.TestExecutionService.ClientID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pfl.test_execute.TestExecutionService.ClientID();
    }

    public static pfl.test_execute.TestExecutionService.ClientID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientID>
        PARSER = new com.google.protobuf.AbstractParser<ClientID>() {
      @java.lang.Override
      public ClientID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClientID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientID> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pfl.test_execute.TestExecutionService.ClientID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Task)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string expKey = 1;</code>
     * @return The expKey.
     */
    java.lang.String getExpKey();
    /**
     * <code>string expKey = 1;</code>
     * @return The bytes for expKey.
     */
    com.google.protobuf.ByteString
        getExpKeyBytes();

    /**
     * <code>string btmStr = 2;</code>
     * @return The btmStr.
     */
    java.lang.String getBtmStr();
    /**
     * <code>string btmStr = 2;</code>
     * @return The bytes for btmStr.
     */
    com.google.protobuf.ByteString
        getBtmStrBytes();

    /**
     * <code>string unittestFunc = 3;</code>
     * @return The unittestFunc.
     */
    java.lang.String getUnittestFunc();
    /**
     * <code>string unittestFunc = 3;</code>
     * @return The bytes for unittestFunc.
     */
    com.google.protobuf.ByteString
        getUnittestFuncBytes();

    /**
     * <code>int32 injectionTimeMs = 4;</code>
     * @return The injectionTimeMs.
     */
    int getInjectionTimeMs();

    /**
     * <code>int32 unittestTimeoutMs = 5;</code>
     * @return The unittestTimeoutMs.
     */
    int getUnittestTimeoutMs();
  }
  /**
   * Protobuf type {@code Task}
   */
  public static final class Task extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Task)
      TaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Task() {
      expKey_ = "";
      btmStr_ = "";
      unittestFunc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Task();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pfl.test_execute.TestExecutionService.internal_static_Task_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pfl.test_execute.TestExecutionService.internal_static_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pfl.test_execute.TestExecutionService.Task.class, pfl.test_execute.TestExecutionService.Task.Builder.class);
    }

    public static final int EXPKEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object expKey_ = "";
    /**
     * <code>string expKey = 1;</code>
     * @return The expKey.
     */
    @java.lang.Override
    public java.lang.String getExpKey() {
      java.lang.Object ref = expKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expKey_ = s;
        return s;
      }
    }
    /**
     * <code>string expKey = 1;</code>
     * @return The bytes for expKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExpKeyBytes() {
      java.lang.Object ref = expKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BTMSTR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object btmStr_ = "";
    /**
     * <code>string btmStr = 2;</code>
     * @return The btmStr.
     */
    @java.lang.Override
    public java.lang.String getBtmStr() {
      java.lang.Object ref = btmStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        btmStr_ = s;
        return s;
      }
    }
    /**
     * <code>string btmStr = 2;</code>
     * @return The bytes for btmStr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBtmStrBytes() {
      java.lang.Object ref = btmStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        btmStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNITTESTFUNC_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object unittestFunc_ = "";
    /**
     * <code>string unittestFunc = 3;</code>
     * @return The unittestFunc.
     */
    @java.lang.Override
    public java.lang.String getUnittestFunc() {
      java.lang.Object ref = unittestFunc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unittestFunc_ = s;
        return s;
      }
    }
    /**
     * <code>string unittestFunc = 3;</code>
     * @return The bytes for unittestFunc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnittestFuncBytes() {
      java.lang.Object ref = unittestFunc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unittestFunc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INJECTIONTIMEMS_FIELD_NUMBER = 4;
    private int injectionTimeMs_ = 0;
    /**
     * <code>int32 injectionTimeMs = 4;</code>
     * @return The injectionTimeMs.
     */
    @java.lang.Override
    public int getInjectionTimeMs() {
      return injectionTimeMs_;
    }

    public static final int UNITTESTTIMEOUTMS_FIELD_NUMBER = 5;
    private int unittestTimeoutMs_ = 0;
    /**
     * <code>int32 unittestTimeoutMs = 5;</code>
     * @return The unittestTimeoutMs.
     */
    @java.lang.Override
    public int getUnittestTimeoutMs() {
      return unittestTimeoutMs_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, expKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(btmStr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, btmStr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unittestFunc_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, unittestFunc_);
      }
      if (injectionTimeMs_ != 0) {
        output.writeInt32(4, injectionTimeMs_);
      }
      if (unittestTimeoutMs_ != 0) {
        output.writeInt32(5, unittestTimeoutMs_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, expKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(btmStr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, btmStr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unittestFunc_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, unittestFunc_);
      }
      if (injectionTimeMs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, injectionTimeMs_);
      }
      if (unittestTimeoutMs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, unittestTimeoutMs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pfl.test_execute.TestExecutionService.Task)) {
        return super.equals(obj);
      }
      pfl.test_execute.TestExecutionService.Task other = (pfl.test_execute.TestExecutionService.Task) obj;

      if (!getExpKey()
          .equals(other.getExpKey())) return false;
      if (!getBtmStr()
          .equals(other.getBtmStr())) return false;
      if (!getUnittestFunc()
          .equals(other.getUnittestFunc())) return false;
      if (getInjectionTimeMs()
          != other.getInjectionTimeMs()) return false;
      if (getUnittestTimeoutMs()
          != other.getUnittestTimeoutMs()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getExpKey().hashCode();
      hash = (37 * hash) + BTMSTR_FIELD_NUMBER;
      hash = (53 * hash) + getBtmStr().hashCode();
      hash = (37 * hash) + UNITTESTFUNC_FIELD_NUMBER;
      hash = (53 * hash) + getUnittestFunc().hashCode();
      hash = (37 * hash) + INJECTIONTIMEMS_FIELD_NUMBER;
      hash = (53 * hash) + getInjectionTimeMs();
      hash = (37 * hash) + UNITTESTTIMEOUTMS_FIELD_NUMBER;
      hash = (53 * hash) + getUnittestTimeoutMs();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pfl.test_execute.TestExecutionService.Task parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pfl.test_execute.TestExecutionService.Task parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pfl.test_execute.TestExecutionService.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pfl.test_execute.TestExecutionService.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pfl.test_execute.TestExecutionService.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pfl.test_execute.TestExecutionService.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pfl.test_execute.TestExecutionService.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pfl.test_execute.TestExecutionService.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pfl.test_execute.TestExecutionService.Task prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Task)
        pfl.test_execute.TestExecutionService.TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pfl.test_execute.TestExecutionService.internal_static_Task_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pfl.test_execute.TestExecutionService.internal_static_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pfl.test_execute.TestExecutionService.Task.class, pfl.test_execute.TestExecutionService.Task.Builder.class);
      }

      // Construct using pfl.test_execute.TestExecutionService.Task.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        expKey_ = "";
        btmStr_ = "";
        unittestFunc_ = "";
        injectionTimeMs_ = 0;
        unittestTimeoutMs_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pfl.test_execute.TestExecutionService.internal_static_Task_descriptor;
      }

      @java.lang.Override
      public pfl.test_execute.TestExecutionService.Task getDefaultInstanceForType() {
        return pfl.test_execute.TestExecutionService.Task.getDefaultInstance();
      }

      @java.lang.Override
      public pfl.test_execute.TestExecutionService.Task build() {
        pfl.test_execute.TestExecutionService.Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pfl.test_execute.TestExecutionService.Task buildPartial() {
        pfl.test_execute.TestExecutionService.Task result = new pfl.test_execute.TestExecutionService.Task(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pfl.test_execute.TestExecutionService.Task result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.expKey_ = expKey_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.btmStr_ = btmStr_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.unittestFunc_ = unittestFunc_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.injectionTimeMs_ = injectionTimeMs_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.unittestTimeoutMs_ = unittestTimeoutMs_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pfl.test_execute.TestExecutionService.Task) {
          return mergeFrom((pfl.test_execute.TestExecutionService.Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pfl.test_execute.TestExecutionService.Task other) {
        if (other == pfl.test_execute.TestExecutionService.Task.getDefaultInstance()) return this;
        if (!other.getExpKey().isEmpty()) {
          expKey_ = other.expKey_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getBtmStr().isEmpty()) {
          btmStr_ = other.btmStr_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getUnittestFunc().isEmpty()) {
          unittestFunc_ = other.unittestFunc_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getInjectionTimeMs() != 0) {
          setInjectionTimeMs(other.getInjectionTimeMs());
        }
        if (other.getUnittestTimeoutMs() != 0) {
          setUnittestTimeoutMs(other.getUnittestTimeoutMs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                expKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                btmStr_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                unittestFunc_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                injectionTimeMs_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                unittestTimeoutMs_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object expKey_ = "";
      /**
       * <code>string expKey = 1;</code>
       * @return The expKey.
       */
      public java.lang.String getExpKey() {
        java.lang.Object ref = expKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string expKey = 1;</code>
       * @return The bytes for expKey.
       */
      public com.google.protobuf.ByteString
          getExpKeyBytes() {
        java.lang.Object ref = expKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string expKey = 1;</code>
       * @param value The expKey to set.
       * @return This builder for chaining.
       */
      public Builder setExpKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        expKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string expKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpKey() {
        expKey_ = getDefaultInstance().getExpKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string expKey = 1;</code>
       * @param value The bytes for expKey to set.
       * @return This builder for chaining.
       */
      public Builder setExpKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        expKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object btmStr_ = "";
      /**
       * <code>string btmStr = 2;</code>
       * @return The btmStr.
       */
      public java.lang.String getBtmStr() {
        java.lang.Object ref = btmStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          btmStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string btmStr = 2;</code>
       * @return The bytes for btmStr.
       */
      public com.google.protobuf.ByteString
          getBtmStrBytes() {
        java.lang.Object ref = btmStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          btmStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string btmStr = 2;</code>
       * @param value The btmStr to set.
       * @return This builder for chaining.
       */
      public Builder setBtmStr(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        btmStr_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string btmStr = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBtmStr() {
        btmStr_ = getDefaultInstance().getBtmStr();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string btmStr = 2;</code>
       * @param value The bytes for btmStr to set.
       * @return This builder for chaining.
       */
      public Builder setBtmStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        btmStr_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object unittestFunc_ = "";
      /**
       * <code>string unittestFunc = 3;</code>
       * @return The unittestFunc.
       */
      public java.lang.String getUnittestFunc() {
        java.lang.Object ref = unittestFunc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unittestFunc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unittestFunc = 3;</code>
       * @return The bytes for unittestFunc.
       */
      public com.google.protobuf.ByteString
          getUnittestFuncBytes() {
        java.lang.Object ref = unittestFunc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unittestFunc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unittestFunc = 3;</code>
       * @param value The unittestFunc to set.
       * @return This builder for chaining.
       */
      public Builder setUnittestFunc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        unittestFunc_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string unittestFunc = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnittestFunc() {
        unittestFunc_ = getDefaultInstance().getUnittestFunc();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string unittestFunc = 3;</code>
       * @param value The bytes for unittestFunc to set.
       * @return This builder for chaining.
       */
      public Builder setUnittestFuncBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        unittestFunc_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int injectionTimeMs_ ;
      /**
       * <code>int32 injectionTimeMs = 4;</code>
       * @return The injectionTimeMs.
       */
      @java.lang.Override
      public int getInjectionTimeMs() {
        return injectionTimeMs_;
      }
      /**
       * <code>int32 injectionTimeMs = 4;</code>
       * @param value The injectionTimeMs to set.
       * @return This builder for chaining.
       */
      public Builder setInjectionTimeMs(int value) {

        injectionTimeMs_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 injectionTimeMs = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearInjectionTimeMs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        injectionTimeMs_ = 0;
        onChanged();
        return this;
      }

      private int unittestTimeoutMs_ ;
      /**
       * <code>int32 unittestTimeoutMs = 5;</code>
       * @return The unittestTimeoutMs.
       */
      @java.lang.Override
      public int getUnittestTimeoutMs() {
        return unittestTimeoutMs_;
      }
      /**
       * <code>int32 unittestTimeoutMs = 5;</code>
       * @param value The unittestTimeoutMs to set.
       * @return This builder for chaining.
       */
      public Builder setUnittestTimeoutMs(int value) {

        unittestTimeoutMs_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 unittestTimeoutMs = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnittestTimeoutMs() {
        bitField0_ = (bitField0_ & ~0x00000010);
        unittestTimeoutMs_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Task)
    }

    // @@protoc_insertion_point(class_scope:Task)
    private static final pfl.test_execute.TestExecutionService.Task DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pfl.test_execute.TestExecutionService.Task();
    }

    public static pfl.test_execute.TestExecutionService.Task getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Task>
        PARSER = new com.google.protobuf.AbstractParser<Task>() {
      @java.lang.Override
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Task> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pfl.test_execute.TestExecutionService.Task getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TaskResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ClientID clientID = 1;</code>
     * @return Whether the clientID field is set.
     */
    boolean hasClientID();
    /**
     * <code>.ClientID clientID = 1;</code>
     * @return The clientID.
     */
    pfl.test_execute.TestExecutionService.ClientID getClientID();
    /**
     * <code>.ClientID clientID = 1;</code>
     */
    pfl.test_execute.TestExecutionService.ClientIDOrBuilder getClientIDOrBuilder();

    /**
     * <code>string expKey = 2;</code>
     * @return The expKey.
     */
    java.lang.String getExpKey();
    /**
     * <code>string expKey = 2;</code>
     * @return The bytes for expKey.
     */
    com.google.protobuf.ByteString
        getExpKeyBytes();

    /**
     * <code>bytes testOutput = 3;</code>
     * @return The testOutput.
     */
    com.google.protobuf.ByteString getTestOutput();
  }
  /**
   * Protobuf type {@code TaskResult}
   */
  public static final class TaskResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TaskResult)
      TaskResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskResult.newBuilder() to construct.
    private TaskResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskResult() {
      expKey_ = "";
      testOutput_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskResult();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pfl.test_execute.TestExecutionService.internal_static_TaskResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pfl.test_execute.TestExecutionService.internal_static_TaskResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pfl.test_execute.TestExecutionService.TaskResult.class, pfl.test_execute.TestExecutionService.TaskResult.Builder.class);
    }

    private int bitField0_;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    private pfl.test_execute.TestExecutionService.ClientID clientID_;
    /**
     * <code>.ClientID clientID = 1;</code>
     * @return Whether the clientID field is set.
     */
    @java.lang.Override
    public boolean hasClientID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ClientID clientID = 1;</code>
     * @return The clientID.
     */
    @java.lang.Override
    public pfl.test_execute.TestExecutionService.ClientID getClientID() {
      return clientID_ == null ? pfl.test_execute.TestExecutionService.ClientID.getDefaultInstance() : clientID_;
    }
    /**
     * <code>.ClientID clientID = 1;</code>
     */
    @java.lang.Override
    public pfl.test_execute.TestExecutionService.ClientIDOrBuilder getClientIDOrBuilder() {
      return clientID_ == null ? pfl.test_execute.TestExecutionService.ClientID.getDefaultInstance() : clientID_;
    }

    public static final int EXPKEY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object expKey_ = "";
    /**
     * <code>string expKey = 2;</code>
     * @return The expKey.
     */
    @java.lang.Override
    public java.lang.String getExpKey() {
      java.lang.Object ref = expKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expKey_ = s;
        return s;
      }
    }
    /**
     * <code>string expKey = 2;</code>
     * @return The bytes for expKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExpKeyBytes() {
      java.lang.Object ref = expKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TESTOUTPUT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString testOutput_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes testOutput = 3;</code>
     * @return The testOutput.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTestOutput() {
      return testOutput_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getClientID());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, expKey_);
      }
      if (!testOutput_.isEmpty()) {
        output.writeBytes(3, testOutput_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getClientID());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, expKey_);
      }
      if (!testOutput_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, testOutput_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pfl.test_execute.TestExecutionService.TaskResult)) {
        return super.equals(obj);
      }
      pfl.test_execute.TestExecutionService.TaskResult other = (pfl.test_execute.TestExecutionService.TaskResult) obj;

      if (hasClientID() != other.hasClientID()) return false;
      if (hasClientID()) {
        if (!getClientID()
            .equals(other.getClientID())) return false;
      }
      if (!getExpKey()
          .equals(other.getExpKey())) return false;
      if (!getTestOutput()
          .equals(other.getTestOutput())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClientID()) {
        hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
        hash = (53 * hash) + getClientID().hashCode();
      }
      hash = (37 * hash) + EXPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getExpKey().hashCode();
      hash = (37 * hash) + TESTOUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getTestOutput().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pfl.test_execute.TestExecutionService.TaskResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pfl.test_execute.TestExecutionService.TaskResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pfl.test_execute.TestExecutionService.TaskResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pfl.test_execute.TestExecutionService.TaskResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaskResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TaskResult)
        pfl.test_execute.TestExecutionService.TaskResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pfl.test_execute.TestExecutionService.internal_static_TaskResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pfl.test_execute.TestExecutionService.internal_static_TaskResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pfl.test_execute.TestExecutionService.TaskResult.class, pfl.test_execute.TestExecutionService.TaskResult.Builder.class);
      }

      // Construct using pfl.test_execute.TestExecutionService.TaskResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getClientIDFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        clientID_ = null;
        if (clientIDBuilder_ != null) {
          clientIDBuilder_.dispose();
          clientIDBuilder_ = null;
        }
        expKey_ = "";
        testOutput_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pfl.test_execute.TestExecutionService.internal_static_TaskResult_descriptor;
      }

      @java.lang.Override
      public pfl.test_execute.TestExecutionService.TaskResult getDefaultInstanceForType() {
        return pfl.test_execute.TestExecutionService.TaskResult.getDefaultInstance();
      }

      @java.lang.Override
      public pfl.test_execute.TestExecutionService.TaskResult build() {
        pfl.test_execute.TestExecutionService.TaskResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pfl.test_execute.TestExecutionService.TaskResult buildPartial() {
        pfl.test_execute.TestExecutionService.TaskResult result = new pfl.test_execute.TestExecutionService.TaskResult(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pfl.test_execute.TestExecutionService.TaskResult result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.clientID_ = clientIDBuilder_ == null
              ? clientID_
              : clientIDBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.expKey_ = expKey_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.testOutput_ = testOutput_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pfl.test_execute.TestExecutionService.TaskResult) {
          return mergeFrom((pfl.test_execute.TestExecutionService.TaskResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pfl.test_execute.TestExecutionService.TaskResult other) {
        if (other == pfl.test_execute.TestExecutionService.TaskResult.getDefaultInstance()) return this;
        if (other.hasClientID()) {
          mergeClientID(other.getClientID());
        }
        if (!other.getExpKey().isEmpty()) {
          expKey_ = other.expKey_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getTestOutput() != com.google.protobuf.ByteString.EMPTY) {
          setTestOutput(other.getTestOutput());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getClientIDFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                expKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                testOutput_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private pfl.test_execute.TestExecutionService.ClientID clientID_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pfl.test_execute.TestExecutionService.ClientID, pfl.test_execute.TestExecutionService.ClientID.Builder, pfl.test_execute.TestExecutionService.ClientIDOrBuilder> clientIDBuilder_;
      /**
       * <code>.ClientID clientID = 1;</code>
       * @return Whether the clientID field is set.
       */
      public boolean hasClientID() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.ClientID clientID = 1;</code>
       * @return The clientID.
       */
      public pfl.test_execute.TestExecutionService.ClientID getClientID() {
        if (clientIDBuilder_ == null) {
          return clientID_ == null ? pfl.test_execute.TestExecutionService.ClientID.getDefaultInstance() : clientID_;
        } else {
          return clientIDBuilder_.getMessage();
        }
      }
      /**
       * <code>.ClientID clientID = 1;</code>
       */
      public Builder setClientID(pfl.test_execute.TestExecutionService.ClientID value) {
        if (clientIDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clientID_ = value;
        } else {
          clientIDBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ClientID clientID = 1;</code>
       */
      public Builder setClientID(
          pfl.test_execute.TestExecutionService.ClientID.Builder builderForValue) {
        if (clientIDBuilder_ == null) {
          clientID_ = builderForValue.build();
        } else {
          clientIDBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ClientID clientID = 1;</code>
       */
      public Builder mergeClientID(pfl.test_execute.TestExecutionService.ClientID value) {
        if (clientIDBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            clientID_ != null &&
            clientID_ != pfl.test_execute.TestExecutionService.ClientID.getDefaultInstance()) {
            getClientIDBuilder().mergeFrom(value);
          } else {
            clientID_ = value;
          }
        } else {
          clientIDBuilder_.mergeFrom(value);
        }
        if (clientID_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.ClientID clientID = 1;</code>
       */
      public Builder clearClientID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientID_ = null;
        if (clientIDBuilder_ != null) {
          clientIDBuilder_.dispose();
          clientIDBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ClientID clientID = 1;</code>
       */
      public pfl.test_execute.TestExecutionService.ClientID.Builder getClientIDBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getClientIDFieldBuilder().getBuilder();
      }
      /**
       * <code>.ClientID clientID = 1;</code>
       */
      public pfl.test_execute.TestExecutionService.ClientIDOrBuilder getClientIDOrBuilder() {
        if (clientIDBuilder_ != null) {
          return clientIDBuilder_.getMessageOrBuilder();
        } else {
          return clientID_ == null ?
              pfl.test_execute.TestExecutionService.ClientID.getDefaultInstance() : clientID_;
        }
      }
      /**
       * <code>.ClientID clientID = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pfl.test_execute.TestExecutionService.ClientID, pfl.test_execute.TestExecutionService.ClientID.Builder, pfl.test_execute.TestExecutionService.ClientIDOrBuilder> 
          getClientIDFieldBuilder() {
        if (clientIDBuilder_ == null) {
          clientIDBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pfl.test_execute.TestExecutionService.ClientID, pfl.test_execute.TestExecutionService.ClientID.Builder, pfl.test_execute.TestExecutionService.ClientIDOrBuilder>(
                  getClientID(),
                  getParentForChildren(),
                  isClean());
          clientID_ = null;
        }
        return clientIDBuilder_;
      }

      private java.lang.Object expKey_ = "";
      /**
       * <code>string expKey = 2;</code>
       * @return The expKey.
       */
      public java.lang.String getExpKey() {
        java.lang.Object ref = expKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string expKey = 2;</code>
       * @return The bytes for expKey.
       */
      public com.google.protobuf.ByteString
          getExpKeyBytes() {
        java.lang.Object ref = expKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string expKey = 2;</code>
       * @param value The expKey to set.
       * @return This builder for chaining.
       */
      public Builder setExpKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        expKey_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string expKey = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpKey() {
        expKey_ = getDefaultInstance().getExpKey();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string expKey = 2;</code>
       * @param value The bytes for expKey to set.
       * @return This builder for chaining.
       */
      public Builder setExpKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        expKey_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString testOutput_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes testOutput = 3;</code>
       * @return The testOutput.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTestOutput() {
        return testOutput_;
      }
      /**
       * <code>bytes testOutput = 3;</code>
       * @param value The testOutput to set.
       * @return This builder for chaining.
       */
      public Builder setTestOutput(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        testOutput_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes testOutput = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestOutput() {
        bitField0_ = (bitField0_ & ~0x00000004);
        testOutput_ = getDefaultInstance().getTestOutput();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TaskResult)
    }

    // @@protoc_insertion_point(class_scope:TaskResult)
    private static final pfl.test_execute.TestExecutionService.TaskResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pfl.test_execute.TestExecutionService.TaskResult();
    }

    public static pfl.test_execute.TestExecutionService.TaskResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskResult>
        PARSER = new com.google.protobuf.AbstractParser<TaskResult>() {
      @java.lang.Override
      public TaskResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TaskResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pfl.test_execute.TestExecutionService.TaskResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientID_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Task_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaskResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032TestExecutionService.proto\032\036google/pro" +
      "tobuf/wrappers.proto\"(\n\010ClientID\022\016\n\006ipAd" +
      "dr\030\001 \001(\t\022\014\n\004uuid\030\002 \001(\t\"p\n\004Task\022\016\n\006expKey" +
      "\030\001 \001(\t\022\016\n\006btmStr\030\002 \001(\t\022\024\n\014unittestFunc\030\003" +
      " \001(\t\022\027\n\017injectionTimeMs\030\004 \001(\005\022\031\n\021unittes" +
      "tTimeoutMs\030\005 \001(\005\"M\n\nTaskResult\022\033\n\010client" +
      "ID\030\001 \001(\0132\t.ClientID\022\016\n\006expKey\030\002 \001(\t\022\022\n\nt" +
      "estOutput\030\003 \001(\0142i\n\rTestExecution\022\035\n\007getT" +
      "ask\022\t.ClientID\032\005.Task\"\000\0229\n\ntaskFinish\022\013." +
      "TaskResult\032\034.google.protobuf.UInt64Value" +
      "\"\000B\022\n\020pfl.test_executeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_ClientID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientID_descriptor,
        new java.lang.String[] { "IpAddr", "Uuid", });
    internal_static_Task_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Task_descriptor,
        new java.lang.String[] { "ExpKey", "BtmStr", "UnittestFunc", "InjectionTimeMs", "UnittestTimeoutMs", });
    internal_static_TaskResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TaskResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaskResult_descriptor,
        new java.lang.String[] { "ClientID", "ExpKey", "TestOutput", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
