# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import TestExecutionService_pb2 as TestExecutionService__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class TestExecutionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTask = channel.unary_unary(
                '/TestExecution/getTask',
                request_serializer=TestExecutionService__pb2.ClientID.SerializeToString,
                response_deserializer=TestExecutionService__pb2.Task.FromString,
                )
        self.taskFinish = channel.unary_unary(
                '/TestExecution/taskFinish',
                request_serializer=TestExecutionService__pb2.TaskResult.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.FromString,
                )


class TestExecutionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def taskFinish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestExecutionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTask': grpc.unary_unary_rpc_method_handler(
                    servicer.getTask,
                    request_deserializer=TestExecutionService__pb2.ClientID.FromString,
                    response_serializer=TestExecutionService__pb2.Task.SerializeToString,
            ),
            'taskFinish': grpc.unary_unary_rpc_method_handler(
                    servicer.taskFinish,
                    request_deserializer=TestExecutionService__pb2.TaskResult.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TestExecution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestExecution(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TestExecution/getTask',
            TestExecutionService__pb2.ClientID.SerializeToString,
            TestExecutionService__pb2.Task.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def taskFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TestExecution/taskFinish',
            TestExecutionService__pb2.TaskResult.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.UInt64Value.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
