# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TestExecutionService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aTestExecutionService.proto\x1a\x1egoogle/protobuf/wrappers.proto\"(\n\x08\x43lientID\x12\x0e\n\x06ipAddr\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"p\n\x04Task\x12\x0e\n\x06\x65xpKey\x18\x01 \x01(\t\x12\x0e\n\x06\x62tmStr\x18\x02 \x01(\t\x12\x14\n\x0cunittestFunc\x18\x03 \x01(\t\x12\x17\n\x0finjectionTimeMs\x18\x04 \x01(\x05\x12\x19\n\x11unittestTimeoutMs\x18\x05 \x01(\x05\"M\n\nTaskResult\x12\x1b\n\x08\x63lientID\x18\x01 \x01(\x0b\x32\t.ClientID\x12\x0e\n\x06\x65xpKey\x18\x02 \x01(\t\x12\x12\n\ntestOutput\x18\x03 \x01(\x0c\x32i\n\rTestExecution\x12\x1d\n\x07getTask\x12\t.ClientID\x1a\x05.Task\"\x00\x12\x39\n\ntaskFinish\x12\x0b.TaskResult\x1a\x1c.google.protobuf.UInt64Value\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TestExecutionService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTID']._serialized_start=62
  _globals['_CLIENTID']._serialized_end=102
  _globals['_TASK']._serialized_start=104
  _globals['_TASK']._serialized_end=216
  _globals['_TASKRESULT']._serialized_start=218
  _globals['_TASKRESULT']._serialized_end=295
  _globals['_TESTEXECUTION']._serialized_start=297
  _globals['_TESTEXECUTION']._serialized_end=402
# @@protoc_insertion_point(module_scope)
